// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projects.Models;

namespace Projects.Migrations
{
    [DbContext(typeof(ProjectsDbContext))]
    partial class ProjectsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Projects.Models.Iteration", b =>
                {
                    b.Property<int>("IterationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedDate");

                    b.Property<DateTime?>("EndDate");

                    b.Property<string>("Name");

                    b.Property<int?>("ReleaseId");

                    b.Property<DateTime?>("StartDate");

                    b.HasKey("IterationId");

                    b.HasIndex("ReleaseId");

                    b.ToTable("Iteration");
                });

            modelBuilder.Entity("Projects.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Projects.Models.Release", b =>
                {
                    b.Property<int>("ReleaseId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ActualReleaseDate");

                    b.Property<DateTime?>("ExpectedReleaseDate");

                    b.Property<string>("Name");

                    b.Property<int>("ProjectId");

                    b.HasKey("ReleaseId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Release");
                });

            modelBuilder.Entity("Projects.Models.Story", b =>
                {
                    b.Property<int>("StoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int?>("IterationId");

                    b.Property<int>("ProjectId");

                    b.Property<int?>("ReleaseId");

                    b.Property<string>("Status");

                    b.HasKey("StoryId");

                    b.HasIndex("IterationId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("Projects.Models.StoryTask", b =>
                {
                    b.Property<int>("StoryTaskId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Status");

                    b.Property<int>("StoryId");

                    b.HasKey("StoryTaskId");

                    b.HasIndex("StoryId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Projects.Models.Iteration", b =>
                {
                    b.HasOne("Projects.Models.Release")
                        .WithMany("Iterations")
                        .HasForeignKey("ReleaseId");
                });

            modelBuilder.Entity("Projects.Models.Release", b =>
                {
                    b.HasOne("Projects.Models.Project")
                        .WithMany("Releases")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Projects.Models.Story", b =>
                {
                    b.HasOne("Projects.Models.Iteration")
                        .WithMany("Stories")
                        .HasForeignKey("IterationId");

                    b.HasOne("Projects.Models.Project")
                        .WithMany("Stories")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Projects.Models.StoryTask", b =>
                {
                    b.HasOne("Projects.Models.Story")
                        .WithMany("Tasks")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
